Rm bulletclass
zzakiullah/Chaos-the-Cat pull request #1
Opened 2020-07-04 22:01 UTC by rabiyamajeed

2020-07-04 22:03 UTC, rabiyamajeed commented
bullet class

2020-07-04 22:10 UTC, zzakiullah requested changes

2020-07-04 22:10 UTC, zzakiullah commented on bullet.cpp
> +// Object.cpp
bullet.cpp lol

2020-07-04 22:10 UTC, zzakiullah commented on bullet.h
> +// Object.cpp
bullet.h lol

2020-07-04 22:16 UTC, zzakiullah approved these changes
Looks good

2020-07-04 22:24 UTC, zzakiullah approved these changes

2020-07-05 19:39 UTC, s-yfang approved these changes

2020-07-05 20:24 UTC, merged